<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vk2"
 *
 * Auto generated by Extension Builder 2015-06-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Virtual Map Forum Extension',
	'description' => 'Das ist eine TYPO3 Erweiterung, welche die Recherche und Visualisierung historischer Karten ermöglicht.',
	'category' => 'plugin',
	'author' => 'Jacob Mendt',
	'author_email' => 'Jacob.Mendt@slub-dresden.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);